[workspace]
members = ["mural","mural-core"]
resolver = "3"

[workspace.package]
version = "0.3.0"
edition = "2024"
authors = ["Devashish Dixit <devashishdxt@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/devashishdxt/mural"

[workspace.dependencies]
drape = "0.1"
similar = "3"
termina = "0.3"
thiserror = "2"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }
