[package]
name = "mural"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ansi-str.workspace = true
mural-core = { path = "../mural-core", version = "0.3.0" }
termina.workspace = true
textwrap.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true

[lints]
workspace = true
